/**
 * Recording the Postgres cases ("I/O" in docs-dev/v3-specs/v3-converter.md):
 * a real `pg` client, wrapped to save each result or error, and the writer
 * of `differential/sqlRecordings.ts`, the module the stand-in replays.
 */
import { literal } from './literal'
import {
  copy,
  recordingKey,
  type PgQuery,
  type RecordedError,
  type Row,
  type SqlRecording,
} from './mocks/postgres'

interface PgClient {
  query(query: PgQuery): Promise<{ rows: Row[] }>
}

/**
 * The client, saving into `saved` the first answer to each query, by its
 * key. What the client returned or threw passes on untouched.
 */
export const recordingClient = (client: PgClient, saved: Map<string, SqlRecording>): PgClient => ({
  query: async ({ text, values }) => {
    const key = recordingKey({ text, values })
    const query = { text, values: copy(values ?? []) }
    try {
      const result = await client.query({ text, values })
      if (!saved.has(key)) saved.set(key, { ...query, rows: copy(result.rows) })
      return result
    } catch (error) {
      if (!saved.has(key)) saved.set(key, { ...query, error: recordedError(error) })
      throw error
    }
  },
})

const recordedError = (error: unknown): RecordedError => {
  const fields = (error ?? {}) as Record<string, unknown>
  const recorded: RecordedError = { message: String(fields.message ?? error) }
  for (const field of ['code', 'table', 'column', 'constraint'] as const)
    if (typeof fields[field] === 'string') recorded[field] = fields[field]
  return recorded
}

/**
 * The module's source, in key order so a new recording's diff shows only
 * what changed. Prettier formats it before it is written.
 */
export const renderRecordings = (recordings: Iterable<SqlRecording>): string => {
  const sorted = [...recordings].sort((a, b) => {
    const [keyA, keyB] = [recordingKey(a), recordingKey(b)]
    return keyA < keyB ? -1 : keyA > keyB ? 1 : 0
  })
  const entries = sorted.map((recording) => {
    try {
      return literal(recording)
    } catch (error) {
      throw new Error(
        `The recording of ${JSON.stringify(recording.text)} ${(error as Error).message}`
      )
    }
  })
  return `/**
 * Generated by \`pnpm differential --record-sql\` from a live Northwind: what
 * the real \`pg\` client answered to each query ("I/O" in
 * docs-dev/v3-specs/v3-converter.md). Never edited by hand.
 */
import type { SqlRecording } from './mocks/postgres'

export const sqlRecordings: SqlRecording[] = [
${entries.join(',\n')}
]
`
}
