/**
 * Recording the Postgres cases ("I/O" in docs-dev/v3-specs/v3-converter.md):
 * a real `pg` client, wrapped to save each result or error, and the writer
 * of `differential/sqlRecordings.ts`, the module the stand-in replays.
 */
import {
  copy,
  recordingKey,
  type PgQuery,
  type RecordedError,
  type Row,
  type SqlRecording,
} from './mocks/postgres'

interface PgClient {
  query(query: PgQuery): Promise<{ rows: Row[] }>
}

/**
 * The client, saving into `saved` the first answer to each query, by its
 * key. What the client returned or threw passes on untouched.
 */
export const recordingClient = (client: PgClient, saved: Map<string, SqlRecording>): PgClient => ({
  query: async ({ text, values }) => {
    const key = recordingKey({ text, values })
    const query = { text, values: copy(values ?? []) }
    try {
      const result = await client.query({ text, values })
      if (!saved.has(key)) saved.set(key, { ...query, rows: copy(result.rows) })
      return result
    } catch (error) {
      if (!saved.has(key)) saved.set(key, { ...query, error: recordedError(error) })
      throw error
    }
  },
})

const recordedError = (error: unknown): RecordedError => {
  const fields = (error ?? {}) as Record<string, unknown>
  const recorded: RecordedError = { message: String(fields.message ?? error) }
  for (const field of ['code', 'table', 'column', 'constraint'] as const)
    if (typeof fields[field] === 'string') recorded[field] = fields[field]
  return recorded
}

/**
 * The module's source, in key order so a new recording's diff shows only
 * what changed. Prettier formats it before it is written.
 */
export const renderRecordings = (recordings: Iterable<SqlRecording>): string => {
  const sorted = [...recordings].sort((a, b) => {
    const [keyA, keyB] = [recordingKey(a), recordingKey(b)]
    return keyA < keyB ? -1 : keyA > keyB ? 1 : 0
  })
  const entries = sorted.map((recording) => render(recording, '', recording.text))
  return `/**
 * Generated by \`pnpm differential --record-sql\` from a live Northwind: what
 * the real \`pg\` client answered to each query ("I/O" in
 * docs-dev/v3-specs/v3-converter.md). Never edited by hand.
 */
import type { SqlRecording } from './mocks/postgres'

export const sqlRecordings: SqlRecording[] = [
${entries.join(',\n')}
]
`
}

/**
 * A value as the literal that evaluates to it, with the type the real
 * client gave it: a `Date` as `new Date('…')`, a `Buffer` (from a `bytea`
 * column) as `Buffer.from('…', 'base64')`, and plain data as literals.
 * Anything else stops the recording, so nothing is written as something it
 * was not. A `Date` is written as its instant, so the replay does not depend
 * on the zone the recording was made in.
 */
const render = (value: unknown, at: string, text: string): string => {
  if (value === null || typeof value === 'string' || typeof value === 'boolean')
    return JSON.stringify(value)
  if (value === undefined) return 'undefined'
  if (typeof value === 'number') return Object.is(value, -0) ? '-0' : String(value)
  if (Array.isArray(value))
    return `[${value.map((item, index) => render(item, `${at}[${index}]`, text)).join(', ')}]`
  if (Buffer.isBuffer(value)) return `Buffer.from('${value.toString('base64')}', 'base64')`
  if (value instanceof Date && !Number.isNaN(value.getTime()))
    return `new Date('${value.toISOString()}')`
  if (isPlainObject(value)) {
    const entries = Object.entries(value).map(
      ([key, v]) => `${JSON.stringify(key)}: ${render(v, `${at}.${key}`, text)}`
    )
    return `{ ${entries.join(', ')} }`
  }
  const kind =
    typeof value === 'object' ? (value.constructor?.name ?? 'object') : `${typeof value} value`
  throw new Error(
    `The recording of ${JSON.stringify(text)} holds a ${kind} at ${at.slice(1)}, ` +
      `which it cannot write as what it is: ${String(value)}`
  )
}

const isPlainObject = (value: unknown): value is Record<string, unknown> => {
  if (value === null || typeof value !== 'object') return false
  const prototype = Object.getPrototypeOf(value)
  return prototype === null || Object.getPrototypeOf(prototype) === null
}
