/**
 * Generated by `pnpm differential --record-sql` from a live Northwind: what
 * the real `pg` client answered to each query ("I/O" in
 * docs-dev/v3-specs/v3-converter.md). Never edited by hand.
 */
import type { SqlRecording } from './mocks/postgres'

export const sqlRecordings: SqlRecording[] = [
  { text: '(SELECT MAX(postal_code) from customers)', values: [], rows: [{ max: 'WX3 6FW' }] },
  {
    text: 'SELECT * FROM employee_table',
    values: [],
    error: { message: 'relation "employee_table" does not exist', code: '42P01' },
  },
  {
    text: 'SELECT * FROM shippers WHERE shipper_id = $1;',
    values: [6],
    rows: [{ shipper_id: 6, company_name: 'DHL', phone: '1-800-225-5345' }],
  },
  {
    text: 'SELECT * FROM shippers;',
    values: [],
    rows: [
      { shipper_id: 1, company_name: 'Speedy Express', phone: '(503) 555-9831' },
      { shipper_id: 2, company_name: 'United Package', phone: '(503) 555-3199' },
      { shipper_id: 3, company_name: 'Federal Shipping', phone: '(503) 555-9931' },
      { shipper_id: 4, company_name: 'Alliance Shippers', phone: '1-800-222-0451' },
      { shipper_id: 5, company_name: 'UPS', phone: '1-800-782-7892' },
      { shipper_id: 6, company_name: 'DHL', phone: '1-800-225-5345' },
    ],
  },
  { text: 'SELECT COUNT(*) FROM employees', values: [], rows: [{ count: '9' }] },
  {
    text: "SELECT contact_name FROM customers where customer_id = 'FAMIA';",
    values: [],
    rows: [{ contact_name: 'Aria Cruz' }],
  },
  {
    text: 'SELECT country FROM customers WHERE postal_code = $1',
    values: ['WX3 6FW'],
    rows: [{ country: 'UK' }],
  },
  {
    text: "SELECT order_id, TO_CHAR(order_date :: DATE, 'Mon dd, yyyy') as order_date, ship_city, ship_country FROM public.orders WHERE customer_id = $1 AND order_id < 10500;",
    values: ['FAMIA'],
    rows: [
      {
        order_id: 10347,
        order_date: 'Nov 06, 1996',
        ship_city: 'Sao Paulo',
        ship_country: 'Brazil',
      },
      {
        order_id: 10386,
        order_date: 'Dec 18, 1996',
        ship_city: 'Sao Paulo',
        ship_country: 'Brazil',
      },
      {
        order_id: 10414,
        order_date: 'Jan 14, 1997',
        ship_city: 'Sao Paulo',
        ship_country: 'Brazil',
      },
    ],
  },
  {
    text: 'SELECT product_name FROM products WHERE category_id = $1 AND supplier_id != $2',
    values: [1, 16],
    rows: [
      { product_name: 'Chai' },
      { product_name: 'Chang' },
      { product_name: 'Guaraná Fantástica' },
      { product_name: 'Côte de Blaye' },
      { product_name: 'Chartreuse verte' },
      { product_name: 'Ipoh Coffee' },
      { product_name: 'Outback Lager' },
      { product_name: 'Rhönbräu Klosterbier' },
      { product_name: 'Lakkalikööri' },
    ],
  },
  {
    text: 'SELECT product_name FROM public.products WHERE category_id = $1 AND supplier_id != $2',
    values: [1, 16],
    rows: [
      { product_name: 'Chai' },
      { product_name: 'Chang' },
      { product_name: 'Guaraná Fantástica' },
      { product_name: 'Côte de Blaye' },
      { product_name: 'Chartreuse verte' },
      { product_name: 'Ipoh Coffee' },
      { product_name: 'Outback Lager' },
      { product_name: 'Rhönbräu Klosterbier' },
      { product_name: 'Lakkalikööri' },
    ],
  },
]
